language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/plates_held

node_js:
  - "v8.9.4"

before_script:
  - psql -c 'create database  plates_held;' -U postgres
  - psql -U postgres -d plates_held -a -f database.sql
  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2